bumpMinorPreMajor: true
handleGHRelease: true
releaseType: java-yoshi
branches:
    - releaseType: java-lts
      branch: 0.25.2-sp
    - branch: java7
    - releaseType: java-backport
      branch: 1.2.x
    - releaseType: java-backport
      branch: 1.12.x
    - releaseType: java-backport
      branch: 1.6.x
    - releaseType: java-backport
      branch: 1.19.x
    - releaseType: java-backport
      branch: 1.20.x
    - releaseType: java-backport
      branch: 1.23.x
    - releaseType: java-backport
      branch: 1.33.x
    - releaseType: java-backport
      branch: 1.36.x
    - branch: protobuf-4.x-rc
      manifest: true
