bumpMinorPreMajor: true
handleGHRelease: true
releaseType: java-yoshi
branches:
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-lts
    branch: 0.25.2-sp
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-yoshi
    branch: java7
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-backport
    branch: 1.2.x
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-backport
    branch: 1.12.x
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-backport
    branch: 1.6.x
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-backport
    branch: 1.19.x
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-backport
    branch: 1.20.x
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-backport
    branch: 1.23.x
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-backport
    branch: 1.33.x
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-backport
    branch: 1.37.x
