/*
 * Copyright 2025 Google LLC
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *    * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 *    * Redistributions in binary form must reproduce the above
 * copyright notice, this list of conditions and the following disclaimer
 * in the documentation and/or other materials provided with the
 * distribution.
 *    * Neither the name of Google LLC nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_side_access_boundary.proto

// Protobuf Java Version: 3.25.5
package com.google.auth.credentialaccessboundary.protobuf;

public final class ClientSideAccessBoundaryProto {
  private ClientSideAccessBoundaryProto() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public interface ClientSideAccessBoundaryRuleOrBuilder
      extends
      // @@protoc_insertion_point(interface_extends:com.google.auth.credentialaccessboundary.proto.ClientSideAccessBoundaryRule)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string available_resource = 1;</code>
     *
     * @return The availableResource.
     */
    java.lang.String getAvailableResource();

    /**
     * <code>string available_resource = 1;</code>
     *
     * @return The bytes for availableResource.
     */
    com.google.protobuf.ByteString getAvailableResourceBytes();

    /**
     * <code>repeated string available_permissions = 2;</code>
     *
     * @return A list containing the availablePermissions.
     */
    java.util.List<java.lang.String> getAvailablePermissionsList();

    /**
     * <code>repeated string available_permissions = 2;</code>
     *
     * @return The count of availablePermissions.
     */
    int getAvailablePermissionsCount();

    /**
     * <code>repeated string available_permissions = 2;</code>
     *
     * @param index The index of the element to return.
     * @return The availablePermissions at the given index.
     */
    java.lang.String getAvailablePermissions(int index);

    /**
     * <code>repeated string available_permissions = 2;</code>
     *
     * @param index The index of the value to return.
     * @return The bytes of the availablePermissions at the given index.
     */
    com.google.protobuf.ByteString getAvailablePermissionsBytes(int index);

    /**
     * <code>.cel.expr.Expr compiled_availability_condition = 4;</code>
     *
     * @return Whether the compiledAvailabilityCondition field is set.
     */
    boolean hasCompiledAvailabilityCondition();

    /**
     * <code>.cel.expr.Expr compiled_availability_condition = 4;</code>
     *
     * @return The compiledAvailabilityCondition.
     */
    dev.cel.expr.Expr getCompiledAvailabilityCondition();

    /** <code>.cel.expr.Expr compiled_availability_condition = 4;</code> */
    dev.cel.expr.ExprOrBuilder getCompiledAvailabilityConditionOrBuilder();
  }

  /**
   * Protobuf type {@code
   * com.google.auth.credentialaccessboundary.proto.ClientSideAccessBoundaryRule}
   */
  public static final class ClientSideAccessBoundaryRule
      extends com.google.protobuf.GeneratedMessageV3
      implements
      // @@protoc_insertion_point(message_implements:com.google.auth.credentialaccessboundary.proto.ClientSideAccessBoundaryRule)
      ClientSideAccessBoundaryRuleOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use ClientSideAccessBoundaryRule.newBuilder() to construct.
    private ClientSideAccessBoundaryRule(
        com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private ClientSideAccessBoundaryRule() {
      availableResource_ = "";
      availablePermissions_ = com.google.protobuf.LazyStringArrayList.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
      return new ClientSideAccessBoundaryRule();
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
          .internal_static_com_google_auth_credentialaccessboundary_proto_ClientSideAccessBoundaryRule_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
          .internal_static_com_google_auth_credentialaccessboundary_proto_ClientSideAccessBoundaryRule_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
                  .ClientSideAccessBoundaryRule.class,
              com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
                  .ClientSideAccessBoundaryRule.Builder.class);
    }

    private int bitField0_;
    public static final int AVAILABLE_RESOURCE_FIELD_NUMBER = 1;

    @SuppressWarnings("serial")
    private volatile java.lang.Object availableResource_ = "";

    /**
     * <code>string available_resource = 1;</code>
     *
     * @return The availableResource.
     */
    @java.lang.Override
    public java.lang.String getAvailableResource() {
      java.lang.Object ref = availableResource_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        availableResource_ = s;
        return s;
      }
    }

    /**
     * <code>string available_resource = 1;</code>
     *
     * @return The bytes for availableResource.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getAvailableResourceBytes() {
      java.lang.Object ref = availableResource_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        availableResource_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AVAILABLE_PERMISSIONS_FIELD_NUMBER = 2;

    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList availablePermissions_ =
        com.google.protobuf.LazyStringArrayList.emptyList();

    /**
     * <code>repeated string available_permissions = 2;</code>
     *
     * @return A list containing the availablePermissions.
     */
    public com.google.protobuf.ProtocolStringList getAvailablePermissionsList() {
      return availablePermissions_;
    }

    /**
     * <code>repeated string available_permissions = 2;</code>
     *
     * @return The count of availablePermissions.
     */
    public int getAvailablePermissionsCount() {
      return availablePermissions_.size();
    }

    /**
     * <code>repeated string available_permissions = 2;</code>
     *
     * @param index The index of the element to return.
     * @return The availablePermissions at the given index.
     */
    public java.lang.String getAvailablePermissions(int index) {
      return availablePermissions_.get(index);
    }

    /**
     * <code>repeated string available_permissions = 2;</code>
     *
     * @param index The index of the value to return.
     * @return The bytes of the availablePermissions at the given index.
     */
    public com.google.protobuf.ByteString getAvailablePermissionsBytes(int index) {
      return availablePermissions_.getByteString(index);
    }

    public static final int COMPILED_AVAILABILITY_CONDITION_FIELD_NUMBER = 4;
    private dev.cel.expr.Expr compiledAvailabilityCondition_;

    /**
     * <code>.cel.expr.Expr compiled_availability_condition = 4;</code>
     *
     * @return Whether the compiledAvailabilityCondition field is set.
     */
    @java.lang.Override
    public boolean hasCompiledAvailabilityCondition() {
      return ((bitField0_ & 0x00000001) != 0);
    }

    /**
     * <code>.cel.expr.Expr compiled_availability_condition = 4;</code>
     *
     * @return The compiledAvailabilityCondition.
     */
    @java.lang.Override
    public dev.cel.expr.Expr getCompiledAvailabilityCondition() {
      return compiledAvailabilityCondition_ == null
          ? dev.cel.expr.Expr.getDefaultInstance()
          : compiledAvailabilityCondition_;
    }

    /** <code>.cel.expr.Expr compiled_availability_condition = 4;</code> */
    @java.lang.Override
    public dev.cel.expr.ExprOrBuilder getCompiledAvailabilityConditionOrBuilder() {
      return compiledAvailabilityCondition_ == null
          ? dev.cel.expr.Expr.getDefaultInstance()
          : compiledAvailabilityCondition_;
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(availableResource_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, availableResource_);
      }
      for (int i = 0; i < availablePermissions_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(
            output, 2, availablePermissions_.getRaw(i));
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(4, getCompiledAvailabilityCondition());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(availableResource_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, availableResource_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < availablePermissions_.size(); i++) {
          dataSize += computeStringSizeNoTag(availablePermissions_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getAvailablePermissionsList().size();
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size +=
            com.google.protobuf.CodedOutputStream.computeMessageSize(
                4, getCompiledAvailabilityCondition());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj
          instanceof
          com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
              .ClientSideAccessBoundaryRule)) {
        return super.equals(obj);
      }
      com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
              .ClientSideAccessBoundaryRule
          other =
              (com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
                      .ClientSideAccessBoundaryRule)
                  obj;

      if (!getAvailableResource().equals(other.getAvailableResource())) return false;
      if (!getAvailablePermissionsList().equals(other.getAvailablePermissionsList())) return false;
      if (hasCompiledAvailabilityCondition() != other.hasCompiledAvailabilityCondition())
        return false;
      if (hasCompiledAvailabilityCondition()) {
        if (!getCompiledAvailabilityCondition().equals(other.getCompiledAvailabilityCondition()))
          return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + AVAILABLE_RESOURCE_FIELD_NUMBER;
      hash = (53 * hash) + getAvailableResource().hashCode();
      if (getAvailablePermissionsCount() > 0) {
        hash = (37 * hash) + AVAILABLE_PERMISSIONS_FIELD_NUMBER;
        hash = (53 * hash) + getAvailablePermissionsList().hashCode();
      }
      if (hasCompiledAvailabilityCondition()) {
        hash = (37 * hash) + COMPILED_AVAILABILITY_CONDITION_FIELD_NUMBER;
        hash = (53 * hash) + getCompiledAvailabilityCondition().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
            .ClientSideAccessBoundaryRule
        parseFrom(java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
            .ClientSideAccessBoundaryRule
        parseFrom(
            java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
            .ClientSideAccessBoundaryRule
        parseFrom(com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
            .ClientSideAccessBoundaryRule
        parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
            .ClientSideAccessBoundaryRule
        parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
            .ClientSideAccessBoundaryRule
        parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
            .ClientSideAccessBoundaryRule
        parseFrom(java.io.InputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
            .ClientSideAccessBoundaryRule
        parseFrom(
            java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
          PARSER, input, extensionRegistry);
    }

    public static com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
            .ClientSideAccessBoundaryRule
        parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }

    public static com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
            .ClientSideAccessBoundaryRule
        parseDelimitedFrom(
            java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
          PARSER, input, extensionRegistry);
    }

    public static com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
            .ClientSideAccessBoundaryRule
        parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
            .ClientSideAccessBoundaryRule
        parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
          PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(
        com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
                .ClientSideAccessBoundaryRule
            prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    /**
     * Protobuf type {@code
     * com.google.auth.credentialaccessboundary.proto.ClientSideAccessBoundaryRule}
     */
    public static final class Builder
        extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
        implements
        // @@protoc_insertion_point(builder_implements:com.google.auth.credentialaccessboundary.proto.ClientSideAccessBoundaryRule)
        com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
            .ClientSideAccessBoundaryRuleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
            .internal_static_com_google_auth_credentialaccessboundary_proto_ClientSideAccessBoundaryRule_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
            .internal_static_com_google_auth_credentialaccessboundary_proto_ClientSideAccessBoundaryRule_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
                    .ClientSideAccessBoundaryRule.class,
                com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
                    .ClientSideAccessBoundaryRule.Builder.class);
      }

      // Construct using
      // com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto.ClientSideAccessBoundaryRule.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
          getCompiledAvailabilityConditionFieldBuilder();
        }
      }

      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        availableResource_ = "";
        availablePermissions_ = com.google.protobuf.LazyStringArrayList.emptyList();
        compiledAvailabilityCondition_ = null;
        if (compiledAvailabilityConditionBuilder_ != null) {
          compiledAvailabilityConditionBuilder_.dispose();
          compiledAvailabilityConditionBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
        return com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
            .internal_static_com_google_auth_credentialaccessboundary_proto_ClientSideAccessBoundaryRule_descriptor;
      }

      @java.lang.Override
      public com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
              .ClientSideAccessBoundaryRule
          getDefaultInstanceForType() {
        return com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
            .ClientSideAccessBoundaryRule.getDefaultInstance();
      }

      @java.lang.Override
      public com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
              .ClientSideAccessBoundaryRule
          build() {
        com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
                .ClientSideAccessBoundaryRule
            result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
              .ClientSideAccessBoundaryRule
          buildPartial() {
        com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
                .ClientSideAccessBoundaryRule
            result =
                new com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
                    .ClientSideAccessBoundaryRule(this);
        if (bitField0_ != 0) {
          buildPartial0(result);
        }
        onBuilt();
        return result;
      }

      private void buildPartial0(
          com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
                  .ClientSideAccessBoundaryRule
              result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.availableResource_ = availableResource_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          availablePermissions_.makeImmutable();
          result.availablePermissions_ = availablePermissions_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.compiledAvailabilityCondition_ =
              compiledAvailabilityConditionBuilder_ == null
                  ? compiledAvailabilityCondition_
                  : compiledAvailabilityConditionBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }

      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
        return super.setField(field, value);
      }

      @java.lang.Override
      public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }

      @java.lang.Override
      public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }

      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index,
          java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }

      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other
            instanceof
            com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
                .ClientSideAccessBoundaryRule) {
          return mergeFrom(
              (com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
                      .ClientSideAccessBoundaryRule)
                  other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(
          com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
                  .ClientSideAccessBoundaryRule
              other) {
        if (other
            == com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
                .ClientSideAccessBoundaryRule.getDefaultInstance()) return this;
        if (!other.getAvailableResource().isEmpty()) {
          availableResource_ = other.availableResource_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.availablePermissions_.isEmpty()) {
          if (availablePermissions_.isEmpty()) {
            availablePermissions_ = other.availablePermissions_;
            bitField0_ |= 0x00000002;
          } else {
            ensureAvailablePermissionsIsMutable();
            availablePermissions_.addAll(other.availablePermissions_);
          }
          onChanged();
        }
        if (other.hasCompiledAvailabilityCondition()) {
          mergeCompiledAvailabilityCondition(other.getCompiledAvailabilityCondition());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10:
                {
                  availableResource_ = input.readStringRequireUtf8();
                  bitField0_ |= 0x00000001;
                  break;
                } // case 10
              case 18:
                {
                  java.lang.String s = input.readStringRequireUtf8();
                  ensureAvailablePermissionsIsMutable();
                  availablePermissions_.add(s);
                  break;
                } // case 18
              case 34:
                {
                  input.readMessage(
                      getCompiledAvailabilityConditionFieldBuilder().getBuilder(),
                      extensionRegistry);
                  bitField0_ |= 0x00000004;
                  break;
                } // case 34
              default:
                {
                  if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                    done = true; // was an endgroup tag
                  }
                  break;
                } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private int bitField0_;

      private java.lang.Object availableResource_ = "";

      /**
       * <code>string available_resource = 1;</code>
       *
       * @return The availableResource.
       */
      public java.lang.String getAvailableResource() {
        java.lang.Object ref = availableResource_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          availableResource_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }

      /**
       * <code>string available_resource = 1;</code>
       *
       * @return The bytes for availableResource.
       */
      public com.google.protobuf.ByteString getAvailableResourceBytes() {
        java.lang.Object ref = availableResource_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
          availableResource_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>string available_resource = 1;</code>
       *
       * @param value The availableResource to set.
       * @return This builder for chaining.
       */
      public Builder setAvailableResource(java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        availableResource_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      /**
       * <code>string available_resource = 1;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearAvailableResource() {
        availableResource_ = getDefaultInstance().getAvailableResource();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      /**
       * <code>string available_resource = 1;</code>
       *
       * @param value The bytes for availableResource to set.
       * @return This builder for chaining.
       */
      public Builder setAvailableResourceBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);
        availableResource_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringArrayList availablePermissions_ =
          com.google.protobuf.LazyStringArrayList.emptyList();

      private void ensureAvailablePermissionsIsMutable() {
        if (!availablePermissions_.isModifiable()) {
          availablePermissions_ =
              new com.google.protobuf.LazyStringArrayList(availablePermissions_);
        }
        bitField0_ |= 0x00000002;
      }

      /**
       * <code>repeated string available_permissions = 2;</code>
       *
       * @return A list containing the availablePermissions.
       */
      public com.google.protobuf.ProtocolStringList getAvailablePermissionsList() {
        availablePermissions_.makeImmutable();
        return availablePermissions_;
      }

      /**
       * <code>repeated string available_permissions = 2;</code>
       *
       * @return The count of availablePermissions.
       */
      public int getAvailablePermissionsCount() {
        return availablePermissions_.size();
      }

      /**
       * <code>repeated string available_permissions = 2;</code>
       *
       * @param index The index of the element to return.
       * @return The availablePermissions at the given index.
       */
      public java.lang.String getAvailablePermissions(int index) {
        return availablePermissions_.get(index);
      }

      /**
       * <code>repeated string available_permissions = 2;</code>
       *
       * @param index The index of the value to return.
       * @return The bytes of the availablePermissions at the given index.
       */
      public com.google.protobuf.ByteString getAvailablePermissionsBytes(int index) {
        return availablePermissions_.getByteString(index);
      }

      /**
       * <code>repeated string available_permissions = 2;</code>
       *
       * @param index The index to set the value at.
       * @param value The availablePermissions to set.
       * @return This builder for chaining.
       */
      public Builder setAvailablePermissions(int index, java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAvailablePermissionsIsMutable();
        availablePermissions_.set(index, value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      /**
       * <code>repeated string available_permissions = 2;</code>
       *
       * @param value The availablePermissions to add.
       * @return This builder for chaining.
       */
      public Builder addAvailablePermissions(java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAvailablePermissionsIsMutable();
        availablePermissions_.add(value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      /**
       * <code>repeated string available_permissions = 2;</code>
       *
       * @param values The availablePermissions to add.
       * @return This builder for chaining.
       */
      public Builder addAllAvailablePermissions(java.lang.Iterable<java.lang.String> values) {
        ensureAvailablePermissionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(values, availablePermissions_);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      /**
       * <code>repeated string available_permissions = 2;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearAvailablePermissions() {
        availablePermissions_ = com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        ;
        onChanged();
        return this;
      }

      /**
       * <code>repeated string available_permissions = 2;</code>
       *
       * @param value The bytes of the availablePermissions to add.
       * @return This builder for chaining.
       */
      public Builder addAvailablePermissionsBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);
        ensureAvailablePermissionsIsMutable();
        availablePermissions_.add(value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private dev.cel.expr.Expr compiledAvailabilityCondition_;
      private com.google.protobuf.SingleFieldBuilderV3<
              dev.cel.expr.Expr, dev.cel.expr.Expr.Builder, dev.cel.expr.ExprOrBuilder>
          compiledAvailabilityConditionBuilder_;

      /**
       * <code>.cel.expr.Expr compiled_availability_condition = 4;</code>
       *
       * @return Whether the compiledAvailabilityCondition field is set.
       */
      public boolean hasCompiledAvailabilityCondition() {
        return ((bitField0_ & 0x00000004) != 0);
      }

      /**
       * <code>.cel.expr.Expr compiled_availability_condition = 4;</code>
       *
       * @return The compiledAvailabilityCondition.
       */
      public dev.cel.expr.Expr getCompiledAvailabilityCondition() {
        if (compiledAvailabilityConditionBuilder_ == null) {
          return compiledAvailabilityCondition_ == null
              ? dev.cel.expr.Expr.getDefaultInstance()
              : compiledAvailabilityCondition_;
        } else {
          return compiledAvailabilityConditionBuilder_.getMessage();
        }
      }

      /** <code>.cel.expr.Expr compiled_availability_condition = 4;</code> */
      public Builder setCompiledAvailabilityCondition(dev.cel.expr.Expr value) {
        if (compiledAvailabilityConditionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          compiledAvailabilityCondition_ = value;
        } else {
          compiledAvailabilityConditionBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      /** <code>.cel.expr.Expr compiled_availability_condition = 4;</code> */
      public Builder setCompiledAvailabilityCondition(dev.cel.expr.Expr.Builder builderForValue) {
        if (compiledAvailabilityConditionBuilder_ == null) {
          compiledAvailabilityCondition_ = builderForValue.build();
        } else {
          compiledAvailabilityConditionBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      /** <code>.cel.expr.Expr compiled_availability_condition = 4;</code> */
      public Builder mergeCompiledAvailabilityCondition(dev.cel.expr.Expr value) {
        if (compiledAvailabilityConditionBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0)
              && compiledAvailabilityCondition_ != null
              && compiledAvailabilityCondition_ != dev.cel.expr.Expr.getDefaultInstance()) {
            getCompiledAvailabilityConditionBuilder().mergeFrom(value);
          } else {
            compiledAvailabilityCondition_ = value;
          }
        } else {
          compiledAvailabilityConditionBuilder_.mergeFrom(value);
        }
        if (compiledAvailabilityCondition_ != null) {
          bitField0_ |= 0x00000004;
          onChanged();
        }
        return this;
      }

      /** <code>.cel.expr.Expr compiled_availability_condition = 4;</code> */
      public Builder clearCompiledAvailabilityCondition() {
        bitField0_ = (bitField0_ & ~0x00000004);
        compiledAvailabilityCondition_ = null;
        if (compiledAvailabilityConditionBuilder_ != null) {
          compiledAvailabilityConditionBuilder_.dispose();
          compiledAvailabilityConditionBuilder_ = null;
        }
        onChanged();
        return this;
      }

      /** <code>.cel.expr.Expr compiled_availability_condition = 4;</code> */
      public dev.cel.expr.Expr.Builder getCompiledAvailabilityConditionBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getCompiledAvailabilityConditionFieldBuilder().getBuilder();
      }

      /** <code>.cel.expr.Expr compiled_availability_condition = 4;</code> */
      public dev.cel.expr.ExprOrBuilder getCompiledAvailabilityConditionOrBuilder() {
        if (compiledAvailabilityConditionBuilder_ != null) {
          return compiledAvailabilityConditionBuilder_.getMessageOrBuilder();
        } else {
          return compiledAvailabilityCondition_ == null
              ? dev.cel.expr.Expr.getDefaultInstance()
              : compiledAvailabilityCondition_;
        }
      }

      /** <code>.cel.expr.Expr compiled_availability_condition = 4;</code> */
      private com.google.protobuf.SingleFieldBuilderV3<
              dev.cel.expr.Expr, dev.cel.expr.Expr.Builder, dev.cel.expr.ExprOrBuilder>
          getCompiledAvailabilityConditionFieldBuilder() {
        if (compiledAvailabilityConditionBuilder_ == null) {
          compiledAvailabilityConditionBuilder_ =
              new com.google.protobuf.SingleFieldBuilderV3<
                  dev.cel.expr.Expr, dev.cel.expr.Expr.Builder, dev.cel.expr.ExprOrBuilder>(
                  getCompiledAvailabilityCondition(), getParentForChildren(), isClean());
          compiledAvailabilityCondition_ = null;
        }
        return compiledAvailabilityConditionBuilder_;
      }

      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }

      // @@protoc_insertion_point(builder_scope:com.google.auth.credentialaccessboundary.proto.ClientSideAccessBoundaryRule)
    }

    // @@protoc_insertion_point(class_scope:com.google.auth.credentialaccessboundary.proto.ClientSideAccessBoundaryRule)
    private static final com.google.auth.credentialaccessboundary.protobuf
            .ClientSideAccessBoundaryProto.ClientSideAccessBoundaryRule
        DEFAULT_INSTANCE;

    static {
      DEFAULT_INSTANCE =
          new com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
              .ClientSideAccessBoundaryRule();
    }

    public static com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
            .ClientSideAccessBoundaryRule
        getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ClientSideAccessBoundaryRule> PARSER =
        new com.google.protobuf.AbstractParser<ClientSideAccessBoundaryRule>() {
          @java.lang.Override
          public ClientSideAccessBoundaryRule parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
            Builder builder = newBuilder();
            try {
              builder.mergeFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
              throw e.setUnfinishedMessage(builder.buildPartial());
            } catch (com.google.protobuf.UninitializedMessageException e) {
              throw e.asInvalidProtocolBufferException()
                  .setUnfinishedMessage(builder.buildPartial());
            } catch (java.io.IOException e) {
              throw new com.google.protobuf.InvalidProtocolBufferException(e)
                  .setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
          }
        };

    public static com.google.protobuf.Parser<ClientSideAccessBoundaryRule> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ClientSideAccessBoundaryRule> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
            .ClientSideAccessBoundaryRule
        getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }
  }

  public interface ClientSideAccessBoundaryOrBuilder
      extends
      // @@protoc_insertion_point(interface_extends:com.google.auth.credentialaccessboundary.proto.ClientSideAccessBoundary)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>
     * repeated .com.google.auth.credentialaccessboundary.proto.ClientSideAccessBoundaryRule access_boundary_rules = 1;
     * </code>
     */
    java.util.List<
            com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
                .ClientSideAccessBoundaryRule>
        getAccessBoundaryRulesList();

    /**
     * <code>
     * repeated .com.google.auth.credentialaccessboundary.proto.ClientSideAccessBoundaryRule access_boundary_rules = 1;
     * </code>
     */
    com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
            .ClientSideAccessBoundaryRule
        getAccessBoundaryRules(int index);

    /**
     * <code>
     * repeated .com.google.auth.credentialaccessboundary.proto.ClientSideAccessBoundaryRule access_boundary_rules = 1;
     * </code>
     */
    int getAccessBoundaryRulesCount();

    /**
     * <code>
     * repeated .com.google.auth.credentialaccessboundary.proto.ClientSideAccessBoundaryRule access_boundary_rules = 1;
     * </code>
     */
    java.util.List<
            ? extends
                com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
                    .ClientSideAccessBoundaryRuleOrBuilder>
        getAccessBoundaryRulesOrBuilderList();

    /**
     * <code>
     * repeated .com.google.auth.credentialaccessboundary.proto.ClientSideAccessBoundaryRule access_boundary_rules = 1;
     * </code>
     */
    com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
            .ClientSideAccessBoundaryRuleOrBuilder
        getAccessBoundaryRulesOrBuilder(int index);
  }

  /**
   * Protobuf type {@code com.google.auth.credentialaccessboundary.proto.ClientSideAccessBoundary}
   */
  public static final class ClientSideAccessBoundary extends com.google.protobuf.GeneratedMessageV3
      implements
      // @@protoc_insertion_point(message_implements:com.google.auth.credentialaccessboundary.proto.ClientSideAccessBoundary)
      ClientSideAccessBoundaryOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use ClientSideAccessBoundary.newBuilder() to construct.
    private ClientSideAccessBoundary(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private ClientSideAccessBoundary() {
      accessBoundaryRules_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
      return new ClientSideAccessBoundary();
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
          .internal_static_com_google_auth_credentialaccessboundary_proto_ClientSideAccessBoundary_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
          .internal_static_com_google_auth_credentialaccessboundary_proto_ClientSideAccessBoundary_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
                  .ClientSideAccessBoundary.class,
              com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
                  .ClientSideAccessBoundary.Builder.class);
    }

    public static final int ACCESS_BOUNDARY_RULES_FIELD_NUMBER = 1;

    @SuppressWarnings("serial")
    private java.util.List<
            com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
                .ClientSideAccessBoundaryRule>
        accessBoundaryRules_;

    /**
     * <code>
     * repeated .com.google.auth.credentialaccessboundary.proto.ClientSideAccessBoundaryRule access_boundary_rules = 1;
     * </code>
     */
    @java.lang.Override
    public java.util.List<
            com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
                .ClientSideAccessBoundaryRule>
        getAccessBoundaryRulesList() {
      return accessBoundaryRules_;
    }

    /**
     * <code>
     * repeated .com.google.auth.credentialaccessboundary.proto.ClientSideAccessBoundaryRule access_boundary_rules = 1;
     * </code>
     */
    @java.lang.Override
    public java.util.List<
            ? extends
                com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
                    .ClientSideAccessBoundaryRuleOrBuilder>
        getAccessBoundaryRulesOrBuilderList() {
      return accessBoundaryRules_;
    }

    /**
     * <code>
     * repeated .com.google.auth.credentialaccessboundary.proto.ClientSideAccessBoundaryRule access_boundary_rules = 1;
     * </code>
     */
    @java.lang.Override
    public int getAccessBoundaryRulesCount() {
      return accessBoundaryRules_.size();
    }

    /**
     * <code>
     * repeated .com.google.auth.credentialaccessboundary.proto.ClientSideAccessBoundaryRule access_boundary_rules = 1;
     * </code>
     */
    @java.lang.Override
    public com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
            .ClientSideAccessBoundaryRule
        getAccessBoundaryRules(int index) {
      return accessBoundaryRules_.get(index);
    }

    /**
     * <code>
     * repeated .com.google.auth.credentialaccessboundary.proto.ClientSideAccessBoundaryRule access_boundary_rules = 1;
     * </code>
     */
    @java.lang.Override
    public com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
            .ClientSideAccessBoundaryRuleOrBuilder
        getAccessBoundaryRulesOrBuilder(int index) {
      return accessBoundaryRules_.get(index);
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
      for (int i = 0; i < accessBoundaryRules_.size(); i++) {
        output.writeMessage(1, accessBoundaryRules_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < accessBoundaryRules_.size(); i++) {
        size +=
            com.google.protobuf.CodedOutputStream.computeMessageSize(
                1, accessBoundaryRules_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj
          instanceof
          com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
              .ClientSideAccessBoundary)) {
        return super.equals(obj);
      }
      com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
              .ClientSideAccessBoundary
          other =
              (com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
                      .ClientSideAccessBoundary)
                  obj;

      if (!getAccessBoundaryRulesList().equals(other.getAccessBoundaryRulesList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getAccessBoundaryRulesCount() > 0) {
        hash = (37 * hash) + ACCESS_BOUNDARY_RULES_FIELD_NUMBER;
        hash = (53 * hash) + getAccessBoundaryRulesList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
            .ClientSideAccessBoundary
        parseFrom(java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
            .ClientSideAccessBoundary
        parseFrom(
            java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
            .ClientSideAccessBoundary
        parseFrom(com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
            .ClientSideAccessBoundary
        parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
            .ClientSideAccessBoundary
        parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
            .ClientSideAccessBoundary
        parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
            .ClientSideAccessBoundary
        parseFrom(java.io.InputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
            .ClientSideAccessBoundary
        parseFrom(
            java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
          PARSER, input, extensionRegistry);
    }

    public static com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
            .ClientSideAccessBoundary
        parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }

    public static com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
            .ClientSideAccessBoundary
        parseDelimitedFrom(
            java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
          PARSER, input, extensionRegistry);
    }

    public static com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
            .ClientSideAccessBoundary
        parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
            .ClientSideAccessBoundary
        parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
          PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(
        com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
                .ClientSideAccessBoundary
            prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    /**
     * Protobuf type {@code com.google.auth.credentialaccessboundary.proto.ClientSideAccessBoundary}
     */
    public static final class Builder
        extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
        implements
        // @@protoc_insertion_point(builder_implements:com.google.auth.credentialaccessboundary.proto.ClientSideAccessBoundary)
        com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
            .ClientSideAccessBoundaryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
            .internal_static_com_google_auth_credentialaccessboundary_proto_ClientSideAccessBoundary_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
            .internal_static_com_google_auth_credentialaccessboundary_proto_ClientSideAccessBoundary_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
                    .ClientSideAccessBoundary.class,
                com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
                    .ClientSideAccessBoundary.Builder.class);
      }

      // Construct using
      // com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto.ClientSideAccessBoundary.newBuilder()
      private Builder() {}

      private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
      }

      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (accessBoundaryRulesBuilder_ == null) {
          accessBoundaryRules_ = java.util.Collections.emptyList();
        } else {
          accessBoundaryRules_ = null;
          accessBoundaryRulesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
        return com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
            .internal_static_com_google_auth_credentialaccessboundary_proto_ClientSideAccessBoundary_descriptor;
      }

      @java.lang.Override
      public com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
              .ClientSideAccessBoundary
          getDefaultInstanceForType() {
        return com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
            .ClientSideAccessBoundary.getDefaultInstance();
      }

      @java.lang.Override
      public com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
              .ClientSideAccessBoundary
          build() {
        com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
                .ClientSideAccessBoundary
            result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
              .ClientSideAccessBoundary
          buildPartial() {
        com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
                .ClientSideAccessBoundary
            result =
                new com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
                    .ClientSideAccessBoundary(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) {
          buildPartial0(result);
        }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(
          com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
                  .ClientSideAccessBoundary
              result) {
        if (accessBoundaryRulesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            accessBoundaryRules_ = java.util.Collections.unmodifiableList(accessBoundaryRules_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.accessBoundaryRules_ = accessBoundaryRules_;
        } else {
          result.accessBoundaryRules_ = accessBoundaryRulesBuilder_.build();
        }
      }

      private void buildPartial0(
          com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
                  .ClientSideAccessBoundary
              result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }

      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
        return super.setField(field, value);
      }

      @java.lang.Override
      public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }

      @java.lang.Override
      public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }

      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index,
          java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }

      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other
            instanceof
            com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
                .ClientSideAccessBoundary) {
          return mergeFrom(
              (com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
                      .ClientSideAccessBoundary)
                  other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(
          com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
                  .ClientSideAccessBoundary
              other) {
        if (other
            == com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
                .ClientSideAccessBoundary.getDefaultInstance()) return this;
        if (accessBoundaryRulesBuilder_ == null) {
          if (!other.accessBoundaryRules_.isEmpty()) {
            if (accessBoundaryRules_.isEmpty()) {
              accessBoundaryRules_ = other.accessBoundaryRules_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureAccessBoundaryRulesIsMutable();
              accessBoundaryRules_.addAll(other.accessBoundaryRules_);
            }
            onChanged();
          }
        } else {
          if (!other.accessBoundaryRules_.isEmpty()) {
            if (accessBoundaryRulesBuilder_.isEmpty()) {
              accessBoundaryRulesBuilder_.dispose();
              accessBoundaryRulesBuilder_ = null;
              accessBoundaryRules_ = other.accessBoundaryRules_;
              bitField0_ = (bitField0_ & ~0x00000001);
              accessBoundaryRulesBuilder_ =
                  com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders
                      ? getAccessBoundaryRulesFieldBuilder()
                      : null;
            } else {
              accessBoundaryRulesBuilder_.addAllMessages(other.accessBoundaryRules_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10:
                {
                  com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
                          .ClientSideAccessBoundaryRule
                      m =
                          input.readMessage(
                              com.google.auth.credentialaccessboundary.protobuf
                                  .ClientSideAccessBoundaryProto.ClientSideAccessBoundaryRule
                                  .parser(),
                              extensionRegistry);
                  if (accessBoundaryRulesBuilder_ == null) {
                    ensureAccessBoundaryRulesIsMutable();
                    accessBoundaryRules_.add(m);
                  } else {
                    accessBoundaryRulesBuilder_.addMessage(m);
                  }
                  break;
                } // case 10
              default:
                {
                  if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                    done = true; // was an endgroup tag
                  }
                  break;
                } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private int bitField0_;

      private java.util.List<
              com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
                  .ClientSideAccessBoundaryRule>
          accessBoundaryRules_ = java.util.Collections.emptyList();

      private void ensureAccessBoundaryRulesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          accessBoundaryRules_ =
              new java.util.ArrayList<
                  com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
                      .ClientSideAccessBoundaryRule>(accessBoundaryRules_);
          bitField0_ |= 0x00000001;
        }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
              com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
                  .ClientSideAccessBoundaryRule,
              com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
                  .ClientSideAccessBoundaryRule.Builder,
              com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
                  .ClientSideAccessBoundaryRuleOrBuilder>
          accessBoundaryRulesBuilder_;

      /**
       * <code>
       * repeated .com.google.auth.credentialaccessboundary.proto.ClientSideAccessBoundaryRule access_boundary_rules = 1;
       * </code>
       */
      public java.util.List<
              com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
                  .ClientSideAccessBoundaryRule>
          getAccessBoundaryRulesList() {
        if (accessBoundaryRulesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(accessBoundaryRules_);
        } else {
          return accessBoundaryRulesBuilder_.getMessageList();
        }
      }

      /**
       * <code>
       * repeated .com.google.auth.credentialaccessboundary.proto.ClientSideAccessBoundaryRule access_boundary_rules = 1;
       * </code>
       */
      public int getAccessBoundaryRulesCount() {
        if (accessBoundaryRulesBuilder_ == null) {
          return accessBoundaryRules_.size();
        } else {
          return accessBoundaryRulesBuilder_.getCount();
        }
      }

      /**
       * <code>
       * repeated .com.google.auth.credentialaccessboundary.proto.ClientSideAccessBoundaryRule access_boundary_rules = 1;
       * </code>
       */
      public com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
              .ClientSideAccessBoundaryRule
          getAccessBoundaryRules(int index) {
        if (accessBoundaryRulesBuilder_ == null) {
          return accessBoundaryRules_.get(index);
        } else {
          return accessBoundaryRulesBuilder_.getMessage(index);
        }
      }

      /**
       * <code>
       * repeated .com.google.auth.credentialaccessboundary.proto.ClientSideAccessBoundaryRule access_boundary_rules = 1;
       * </code>
       */
      public Builder setAccessBoundaryRules(
          int index,
          com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
                  .ClientSideAccessBoundaryRule
              value) {
        if (accessBoundaryRulesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAccessBoundaryRulesIsMutable();
          accessBoundaryRules_.set(index, value);
          onChanged();
        } else {
          accessBoundaryRulesBuilder_.setMessage(index, value);
        }
        return this;
      }

      /**
       * <code>
       * repeated .com.google.auth.credentialaccessboundary.proto.ClientSideAccessBoundaryRule access_boundary_rules = 1;
       * </code>
       */
      public Builder setAccessBoundaryRules(
          int index,
          com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
                  .ClientSideAccessBoundaryRule.Builder
              builderForValue) {
        if (accessBoundaryRulesBuilder_ == null) {
          ensureAccessBoundaryRulesIsMutable();
          accessBoundaryRules_.set(index, builderForValue.build());
          onChanged();
        } else {
          accessBoundaryRulesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }

      /**
       * <code>
       * repeated .com.google.auth.credentialaccessboundary.proto.ClientSideAccessBoundaryRule access_boundary_rules = 1;
       * </code>
       */
      public Builder addAccessBoundaryRules(
          com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
                  .ClientSideAccessBoundaryRule
              value) {
        if (accessBoundaryRulesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAccessBoundaryRulesIsMutable();
          accessBoundaryRules_.add(value);
          onChanged();
        } else {
          accessBoundaryRulesBuilder_.addMessage(value);
        }
        return this;
      }

      /**
       * <code>
       * repeated .com.google.auth.credentialaccessboundary.proto.ClientSideAccessBoundaryRule access_boundary_rules = 1;
       * </code>
       */
      public Builder addAccessBoundaryRules(
          int index,
          com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
                  .ClientSideAccessBoundaryRule
              value) {
        if (accessBoundaryRulesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAccessBoundaryRulesIsMutable();
          accessBoundaryRules_.add(index, value);
          onChanged();
        } else {
          accessBoundaryRulesBuilder_.addMessage(index, value);
        }
        return this;
      }

      /**
       * <code>
       * repeated .com.google.auth.credentialaccessboundary.proto.ClientSideAccessBoundaryRule access_boundary_rules = 1;
       * </code>
       */
      public Builder addAccessBoundaryRules(
          com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
                  .ClientSideAccessBoundaryRule.Builder
              builderForValue) {
        if (accessBoundaryRulesBuilder_ == null) {
          ensureAccessBoundaryRulesIsMutable();
          accessBoundaryRules_.add(builderForValue.build());
          onChanged();
        } else {
          accessBoundaryRulesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }

      /**
       * <code>
       * repeated .com.google.auth.credentialaccessboundary.proto.ClientSideAccessBoundaryRule access_boundary_rules = 1;
       * </code>
       */
      public Builder addAccessBoundaryRules(
          int index,
          com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
                  .ClientSideAccessBoundaryRule.Builder
              builderForValue) {
        if (accessBoundaryRulesBuilder_ == null) {
          ensureAccessBoundaryRulesIsMutable();
          accessBoundaryRules_.add(index, builderForValue.build());
          onChanged();
        } else {
          accessBoundaryRulesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }

      /**
       * <code>
       * repeated .com.google.auth.credentialaccessboundary.proto.ClientSideAccessBoundaryRule access_boundary_rules = 1;
       * </code>
       */
      public Builder addAllAccessBoundaryRules(
          java.lang.Iterable<
                  ? extends
                      com.google.auth.credentialaccessboundary.protobuf
                          .ClientSideAccessBoundaryProto.ClientSideAccessBoundaryRule>
              values) {
        if (accessBoundaryRulesBuilder_ == null) {
          ensureAccessBoundaryRulesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(values, accessBoundaryRules_);
          onChanged();
        } else {
          accessBoundaryRulesBuilder_.addAllMessages(values);
        }
        return this;
      }

      /**
       * <code>
       * repeated .com.google.auth.credentialaccessboundary.proto.ClientSideAccessBoundaryRule access_boundary_rules = 1;
       * </code>
       */
      public Builder clearAccessBoundaryRules() {
        if (accessBoundaryRulesBuilder_ == null) {
          accessBoundaryRules_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          accessBoundaryRulesBuilder_.clear();
        }
        return this;
      }

      /**
       * <code>
       * repeated .com.google.auth.credentialaccessboundary.proto.ClientSideAccessBoundaryRule access_boundary_rules = 1;
       * </code>
       */
      public Builder removeAccessBoundaryRules(int index) {
        if (accessBoundaryRulesBuilder_ == null) {
          ensureAccessBoundaryRulesIsMutable();
          accessBoundaryRules_.remove(index);
          onChanged();
        } else {
          accessBoundaryRulesBuilder_.remove(index);
        }
        return this;
      }

      /**
       * <code>
       * repeated .com.google.auth.credentialaccessboundary.proto.ClientSideAccessBoundaryRule access_boundary_rules = 1;
       * </code>
       */
      public com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
              .ClientSideAccessBoundaryRule.Builder
          getAccessBoundaryRulesBuilder(int index) {
        return getAccessBoundaryRulesFieldBuilder().getBuilder(index);
      }

      /**
       * <code>
       * repeated .com.google.auth.credentialaccessboundary.proto.ClientSideAccessBoundaryRule access_boundary_rules = 1;
       * </code>
       */
      public com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
              .ClientSideAccessBoundaryRuleOrBuilder
          getAccessBoundaryRulesOrBuilder(int index) {
        if (accessBoundaryRulesBuilder_ == null) {
          return accessBoundaryRules_.get(index);
        } else {
          return accessBoundaryRulesBuilder_.getMessageOrBuilder(index);
        }
      }

      /**
       * <code>
       * repeated .com.google.auth.credentialaccessboundary.proto.ClientSideAccessBoundaryRule access_boundary_rules = 1;
       * </code>
       */
      public java.util.List<
              ? extends
                  com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
                      .ClientSideAccessBoundaryRuleOrBuilder>
          getAccessBoundaryRulesOrBuilderList() {
        if (accessBoundaryRulesBuilder_ != null) {
          return accessBoundaryRulesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(accessBoundaryRules_);
        }
      }

      /**
       * <code>
       * repeated .com.google.auth.credentialaccessboundary.proto.ClientSideAccessBoundaryRule access_boundary_rules = 1;
       * </code>
       */
      public com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
              .ClientSideAccessBoundaryRule.Builder
          addAccessBoundaryRulesBuilder() {
        return getAccessBoundaryRulesFieldBuilder()
            .addBuilder(
                com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
                    .ClientSideAccessBoundaryRule.getDefaultInstance());
      }

      /**
       * <code>
       * repeated .com.google.auth.credentialaccessboundary.proto.ClientSideAccessBoundaryRule access_boundary_rules = 1;
       * </code>
       */
      public com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
              .ClientSideAccessBoundaryRule.Builder
          addAccessBoundaryRulesBuilder(int index) {
        return getAccessBoundaryRulesFieldBuilder()
            .addBuilder(
                index,
                com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
                    .ClientSideAccessBoundaryRule.getDefaultInstance());
      }

      /**
       * <code>
       * repeated .com.google.auth.credentialaccessboundary.proto.ClientSideAccessBoundaryRule access_boundary_rules = 1;
       * </code>
       */
      public java.util.List<
              com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
                  .ClientSideAccessBoundaryRule.Builder>
          getAccessBoundaryRulesBuilderList() {
        return getAccessBoundaryRulesFieldBuilder().getBuilderList();
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
              com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
                  .ClientSideAccessBoundaryRule,
              com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
                  .ClientSideAccessBoundaryRule.Builder,
              com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
                  .ClientSideAccessBoundaryRuleOrBuilder>
          getAccessBoundaryRulesFieldBuilder() {
        if (accessBoundaryRulesBuilder_ == null) {
          accessBoundaryRulesBuilder_ =
              new com.google.protobuf.RepeatedFieldBuilderV3<
                  com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
                      .ClientSideAccessBoundaryRule,
                  com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
                      .ClientSideAccessBoundaryRule.Builder,
                  com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
                      .ClientSideAccessBoundaryRuleOrBuilder>(
                  accessBoundaryRules_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          accessBoundaryRules_ = null;
        }
        return accessBoundaryRulesBuilder_;
      }

      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }

      // @@protoc_insertion_point(builder_scope:com.google.auth.credentialaccessboundary.proto.ClientSideAccessBoundary)
    }

    // @@protoc_insertion_point(class_scope:com.google.auth.credentialaccessboundary.proto.ClientSideAccessBoundary)
    private static final com.google.auth.credentialaccessboundary.protobuf
            .ClientSideAccessBoundaryProto.ClientSideAccessBoundary
        DEFAULT_INSTANCE;

    static {
      DEFAULT_INSTANCE =
          new com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
              .ClientSideAccessBoundary();
    }

    public static com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
            .ClientSideAccessBoundary
        getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ClientSideAccessBoundary> PARSER =
        new com.google.protobuf.AbstractParser<ClientSideAccessBoundary>() {
          @java.lang.Override
          public ClientSideAccessBoundary parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
            Builder builder = newBuilder();
            try {
              builder.mergeFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
              throw e.setUnfinishedMessage(builder.buildPartial());
            } catch (com.google.protobuf.UninitializedMessageException e) {
              throw e.asInvalidProtocolBufferException()
                  .setUnfinishedMessage(builder.buildPartial());
            } catch (java.io.IOException e) {
              throw new com.google.protobuf.InvalidProtocolBufferException(e)
                  .setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
          }
        };

    public static com.google.protobuf.Parser<ClientSideAccessBoundary> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ClientSideAccessBoundary> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.auth.credentialaccessboundary.protobuf.ClientSideAccessBoundaryProto
            .ClientSideAccessBoundary
        getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }
  }

  private static final com.google.protobuf.Descriptors.Descriptor
      internal_static_com_google_auth_credentialaccessboundary_proto_ClientSideAccessBoundaryRule_descriptor;
  private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_google_auth_credentialaccessboundary_proto_ClientSideAccessBoundaryRule_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
      internal_static_com_google_auth_credentialaccessboundary_proto_ClientSideAccessBoundary_descriptor;
  private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_google_auth_credentialaccessboundary_proto_ClientSideAccessBoundary_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n!client_side_access_boundary.proto\022.com"
          + ".google.auth.credentialaccessboundary.pr"
          + "oto\032\025cel/expr/syntax.proto\"\222\001\n\034ClientSid"
          + "eAccessBoundaryRule\022\032\n\022available_resourc"
          + "e\030\001 \001(\t\022\035\n\025available_permissions\030\002 \003(\t\0227"
          + "\n\037compiled_availability_condition\030\004 \001(\0132"
          + "\016.cel.expr.Expr\"\207\001\n\030ClientSideAccessBoun"
          + "dary\022k\n\025access_boundary_rules\030\001 \003(\0132L.co"
          + "m.google.auth.credentialaccessboundary.p"
          + "roto.ClientSideAccessBoundaryRuleBT\n1com"
          + ".google.auth.credentialaccessboundary.pr"
          + "otobufB\035ClientSideAccessBoundaryProtoP\000b"
          + "\006proto3"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
              dev.cel.expr.SyntaxProto.getDescriptor(),
            });
    internal_static_com_google_auth_credentialaccessboundary_proto_ClientSideAccessBoundaryRule_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_com_google_auth_credentialaccessboundary_proto_ClientSideAccessBoundaryRule_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_com_google_auth_credentialaccessboundary_proto_ClientSideAccessBoundaryRule_descriptor,
            new java.lang.String[] {
              "AvailableResource", "AvailablePermissions", "CompiledAvailabilityCondition",
            });
    internal_static_com_google_auth_credentialaccessboundary_proto_ClientSideAccessBoundary_descriptor =
        getDescriptor().getMessageTypes().get(1);
    internal_static_com_google_auth_credentialaccessboundary_proto_ClientSideAccessBoundary_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_com_google_auth_credentialaccessboundary_proto_ClientSideAccessBoundary_descriptor,
            new java.lang.String[] {
              "AccessBoundaryRules",
            });
    dev.cel.expr.SyntaxProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
